version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 3000000000
    ports:
      - 35021:80
    networks:
      - default

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - default
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
  
  mailhog:
    image: jcalonso/mailhog:latest
    restart: always
    networks:
      - default
    ports:
      - 1025:1025
      - 35022:8025

networks:
  default:
    name: local-stack
    external: true

volumes:
  db-data: