version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 3000000000
    ports:
      - 35021:80
    networks:
      - default

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - default
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  mailhog:
    image: jcalonso/mailhog:latest
    restart: always
    networks:
      - default
    ports:
      - 1025:1025
      - 35022:8025

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio_root
      MINIO_ROOT_PASSWORD: minio_secret
    command: minio server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    networks:
      default:
        aliases:
          - local.minio

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - default
    entrypoint: >
      /bin/sh -c " sleep 3s; /usr/bin/mc config host add myminio http://minio:9000 minio_root minio_secret; /usr/bin/mc mb myminio/local; /usr/bin/mc policy set public myminio/local; exit 0; "

networks:
  default:
    name: local-stack
    external: true

volumes:
  db-data:
  minio-data:
