#!/bin/bash

# Print Links ...
tput setaf 7; 
echo "Mysql:   local-stack:34025 root secret"
echo "Redis:   local-stack:6379"
echo "Mailhog: local-stack:1025"
tput setaf 2; 
echo "Sites:"
tput setaf 7; 
echo "Mailhog UI: http://127.0.0.1:34025"